/**
 * docusaurus.ts — Collection adapter for Docusaurus AUTOGENERATED
 * sidebars. https://docusaurus.io/docs/sidebar/autogenerated
 *
 * NAV MODEL: the hierarchy IS the directory tree. A folder is a
 * category; its label/position come from `_category_.json` (`label`,
 * `position`) or, failing that, from its category-index doc
 * (`index.md`, `README.md`, or `<dirname>.md` — absorbed into the
 * category, never shown as a child), else the folder name. A doc's
 * label is `sidebar_label` ?? `title` ?? first `# heading` ?? file
 * name. Siblings sort by
 * explicit position (`sidebar_position` / category `position`) first,
 * then alphabetically by file name. Number prefixes (`01-intro.md`)
 * are treated literally in v1 (zero-padded prefixes still order
 * correctly; a warning notes the limitation).
 *
 * planChanges emits minimal edits:
 * - reorder → renumber the group's sidebar_position / category
 *   `position` only when the induced order differs
 * - rename doc → `sidebar_label` (title/headings untouched); rename
 *   category → `_category_.json` `label` (file created if absent)
 * - cross-folder move → FileChange kind:"move" (+ a links-may-break
 *   warning; slugs and relative links are not rewritten in v1)
 * - removal from the model → `unlisted: true` (Docusaurus ≥ 3; files
 *   are never deleted)
 * - a doc gaining children → converted to a category: the doc moves
 *   to `<name>/index.md` and the children move inside
 * - new in-app nodes → stub doc / `_category_.json` creation
 * `_category_.json` is edited as parsed JSON re-emitted with 2-space
 * indent (the files are tiny and machine-shaped); unknown keys like
 * `collapsed`/`className` are preserved verbatim as values.
 */

import yaml from "js-yaml";
import { newId } from "@/model/id";
import type { Section, TocDocument, Topic } from "@/model/types";
import {
  applyFrontmatterEdits,
  applyYamlFileEdits,
  dumpScalar,
  parseFrontmatter,
  type FrontmatterEdits,
} from "../frontmatter";
import { slugify, targetFromModel, type TargetNode } from "../target";
import { navHeadOf, toNavHeads } from "../navHead";
import {
  buildLinkIndex,
  inboundCount,
  UNSTAMPED,
  type LinkIndex,
  type LinkSpecies,
} from "../linkIndex";
import type {
  CollectionAdapter,
  CollectionParseResult,
  CollectionPlanResult,
  CollectionWarning,
  FileChange,
  FilesSnapshot,
} from "../types";

export const DOCUSAURUS_FORMAT_ID = "docusaurus";

const DOC_RE = /\.(md|mdx)$/i;
/** New categories are created as JSON; both spellings are read and
 *  edited (yml via byte-preserving line surgery — comments survive). */
const CATEGORY = "_category_.json";
const CATEGORY_RE = /^_category_\.(json|ya?ml)$/;

function dirOf(path: string): string {
  const i = path.lastIndexOf("/");
  return i < 0 ? "" : path.slice(0, i);
}
function baseOf(path: string): string {
  const i = path.lastIndexOf("/");
  return i < 0 ? path : path.slice(i + 1);
}
function join(dir: string, name: string): string {
  return dir === "" ? name : `${dir}/${name}`;
}

// ── Scan: files → doc/dir entries ───────────────────────────

interface DocEntry {
  kind: "doc";
  path: string;
  /** File name without extension (the alphabetical sort key). */
  base: string;
  ext: string; // ".md" | ".mdx" (original casing preserved)
  parentDir: string;
  title?: string;
  sidebarLabel?: string;
  position?: number;
  hasPositionKey: boolean;
  hasLabelKey: boolean;
  /** unlisted/draft — kept out of the nav, never re-hidden. */
  excluded: boolean;
}

interface DirEntry {
  kind: "dir";
  path: string;
  base: string;
  parentDir: string;
  categoryPath?: string;
  categoryKind?: "json" | "yml";
  /** Parsed _category_ object (undefined when absent/broken). */
  category?: Record<string, unknown>;
  categoryBroken: boolean;
  /** Absorbed category-index doc (index/README/<dirname>). */
  index?: DocEntry;
}

interface Scan {
  docs: Map<string, DocEntry>;
  dirs: Map<string, DirEntry>;
  /** VISIBLE docs by containing dir (includes absorbed indexes). */
  docsInDir: Map<string, DocEntry[]>;
  dirsInDir: Map<string, DirEntry[]>;
  /** Dirs with at least one visible doc somewhere below. */
  visibleDirs: Set<string>;
  warnings: CollectionWarning[];
}

function scanFiles(files: FilesSnapshot): Scan {
  const warnings: CollectionWarning[] = [];
  const docs = new Map<string, DocEntry>();
  const categoryByDir = new Map<
    string,
    { path: string; kind: "json" | "yml"; data: Record<string, unknown> | null }
  >();

  for (const path of Object.keys(files).sort()) {
    if (CATEGORY_RE.test(baseOf(path))) {
      const kind = baseOf(path) === CATEGORY ? "json" : "yml";
      let data: Record<string, unknown> | null = null;
      try {
        const parsed: unknown =
          kind === "json"
            ? JSON.parse(files[path]!)
            : yaml.load(files[path]!, { json: true });
        if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
          data = parsed as Record<string, unknown>;
        }
      } catch {
        data = null;
      }
      if (data === null) {
        warnings.push({
          kind: "broken-category",
          detail: `${path}: not a ${kind === "json" ? "JSON" : "YAML"} mapping`,
        });
      }
      const existing = categoryByDir.get(dirOf(path));
      if (existing) {
        // Docusaurus reads one metadata file per folder — prefer json
        warnings.push({
          kind: "duplicate-category",
          detail: `${dirOf(path)}/: has both _category_.json and _category_.yml — using .json`,
        });
        if (existing.kind === "json") continue;
      }
      categoryByDir.set(dirOf(path), { path, kind, data });
      continue;
    }
    if (!DOC_RE.test(path)) continue;

    const name = baseOf(path);
    const base = name.replace(DOC_RE, "");
    const block = parseFrontmatter(files[path]!);
    const fm = block?.data ?? {};
    // Docusaurus derives a doc's title from its first `# heading` when
    // frontmatter has none — real docs rely on this heavily. The body
    // starts after the closing fence (block.rest's first line).
    const body = block ? block.rest.split(/\r?\n/).slice(1).join("\n") : files[path]!;
    const title = fm.title != null ? String(fm.title) : firstHeading(body);
    let position: number | undefined;
    if (typeof fm.sidebar_position === "number") {
      position = fm.sidebar_position;
    } else if (fm.sidebar_position !== undefined) {
      warnings.push({
        kind: "bad-position",
        detail: `${path}: sidebar_position is not a number — ignored`,
      });
    }
    docs.set(path, {
      kind: "doc",
      path,
      base,
      ext: name.slice(base.length),
      parentDir: dirOf(path),
      title,
      sidebarLabel: fm.sidebar_label != null ? String(fm.sidebar_label) : undefined,
      position,
      hasPositionKey: fm.sidebar_position !== undefined,
      hasLabelKey: fm.sidebar_label !== undefined,
      // underscore-prefixed files are partials — Docusaurus keeps them
      // out of autogenerated sidebars
      excluded: fm.unlisted === true || fm.draft === true || name.startsWith("_"),
    });
  }

  // every dir holding an ingested file (at any depth) is a candidate
  const dirPaths = new Set<string>();
  const addAncestors = (p: string): void => {
    let d = dirOf(p);
    while (d !== "" && !dirPaths.has(d)) {
      dirPaths.add(d);
      d = dirOf(d);
    }
  };
  for (const p of docs.keys()) addAncestors(p);
  for (const { path } of categoryByDir.values()) addAncestors(path);

  const dirs = new Map<string, DirEntry>();
  for (const path of [...dirPaths].sort()) {
    const cat = categoryByDir.get(path);
    dirs.set(path, {
      kind: "dir",
      path,
      base: baseOf(path),
      parentDir: dirOf(path),
      categoryPath: cat?.path,
      categoryKind: cat?.kind,
      category: cat?.data ?? undefined,
      categoryBroken: cat !== undefined && cat.data === null,
    });
  }

  const docsInDir = new Map<string, DocEntry[]>();
  for (const d of docs.values()) {
    if (d.excluded) continue;
    docsInDir.set(d.parentDir, [...(docsInDir.get(d.parentDir) ?? []), d]);
  }
  const dirsInDir = new Map<string, DirEntry[]>();
  for (const dir of dirs.values()) {
    dirsInDir.set(dir.parentDir, [...(dirsInDir.get(dir.parentDir) ?? []), dir]);
  }

  // category-index absorption (index > README > <dirname>)
  const indexRank = (d: DocEntry, dirBase: string): number => {
    const b = d.base.toLowerCase();
    if (b === "index") return 0;
    if (b === "readme") return 1;
    if (b === dirBase.toLowerCase()) return 2;
    return 9;
  };
  for (const dir of dirs.values()) {
    const cands = (docsInDir.get(dir.path) ?? [])
      .map((d) => ({ d, rank: indexRank(d, dir.base) }))
      .filter((x) => x.rank < 9)
      .sort((a, b) => a.rank - b.rank || (a.d.path < b.d.path ? -1 : 1));
    dir.index = cands[0]?.d;
  }

  const visibleDirs = new Set<string>();
  const isVisible = (dir: DirEntry): boolean => {
    if (visibleDirs.has(dir.path)) return true;
    const visible =
      (docsInDir.get(dir.path) ?? []).length > 0 ||
      (dirsInDir.get(dir.path) ?? []).some(isVisible);
    if (visible) visibleDirs.add(dir.path);
    return visible;
  };
  for (const dir of dirs.values()) {
    if (!isVisible(dir) && dir.categoryPath) {
      warnings.push({
        kind: "empty-category",
        detail: `${dir.path}/: category has no visible docs — not shown`,
      });
    }
  }

  if (
    [...docs.values()].some((d) => /^\d+-/.test(d.base)) ||
    [...dirs.values()].some((d) => /^\d+-/.test(d.base))
  ) {
    warnings.push({
      kind: "number-prefix",
      detail:
        "number-prefixed names (01-intro.md) are ordered literally, not by parsed prefix — zero-pad prefixes for correct order",
    });
  }

  return { docs, dirs, docsInDir, dirsInDir, visibleDirs, warnings };
}

/** First ATX `# heading` outside code fences. Trailing `{#anchor}`
 *  ids and closing hashes are stripped. Setext (===) headings and JSX
 *  <h1> are out of scope — the filename fallback still applies. */
function firstHeading(body: string): string | undefined {
  let fenced = false;
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trimEnd();
    if (/^(```|~~~)/.test(line.trimStart())) {
      fenced = !fenced;
      continue;
    }
    if (fenced) continue;
    const m = line.match(/^#[ \t]+(.+?)$/);
    if (m) {
      const text = m[1]!
        .replace(/\s*\{#[^}]*\}\s*$/, "")
        .replace(/\s+#+\s*$/, "")
        .trim();
      return text || undefined;
    }
  }
  return undefined;
}

function docLabel(d: DocEntry): string {
  return d.sidebarLabel ?? d.title ?? d.base;
}
function dirLabel(dir: DirEntry): string {
  const cat = typeof dir.category?.label === "string" ? dir.category.label : undefined;
  return cat ?? dir.index?.sidebarLabel ?? dir.index?.title ?? dir.base;
}
function dirPosition(dir: DirEntry): number | undefined {
  const cat =
    typeof dir.category?.position === "number" ? dir.category.position : undefined;
  return cat ?? dir.index?.position;
}

/** The Docusaurus sibling comparator (also the planner's oracle). */
interface OrderKey {
  position?: number;
  base: string;
  path: string;
}
function compareOrder(a: OrderKey, b: OrderKey): number {
  if (a.position !== undefined && b.position === undefined) return -1;
  if (a.position === undefined && b.position !== undefined) return 1;
  if (a.position !== undefined && b.position !== undefined && a.position !== b.position) {
    return a.position < b.position ? -1 : 1;
  }
  if (a.base !== b.base) return a.base < b.base ? -1 : 1;
  return a.path < b.path ? -1 : 1;
}

function sortedChildren(scan: Scan, dirPath: string): (DocEntry | DirEntry)[] {
  const dirEntry = scan.dirs.get(dirPath);
  const docs = (scan.docsInDir.get(dirPath) ?? []).filter((d) => d !== dirEntry?.index);
  const dirs = (scan.dirsInDir.get(dirPath) ?? []).filter((d) =>
    scan.visibleDirs.has(d.path),
  );
  const key = (e: DocEntry | DirEntry): OrderKey =>
    e.kind === "doc"
      ? { position: e.position, base: e.base, path: e.path }
      : { position: dirPosition(e), base: e.base, path: e.path };
  return [...docs, ...dirs].sort((a, b) => compareOrder(key(a), key(b)));
}

// ── parse → model ───────────────────────────────────────────

function parse(files: FilesSnapshot, rootName: string): CollectionParseResult {
  const scan = scanFiles(files);

  const docTopic = (d: DocEntry): Topic => ({
    id: newId(),
    title: docLabel(d),
    path: d.path,
    children: [],
  });
  const dirTopic = (dir: DirEntry): Topic => ({
    id: newId(),
    title: dirLabel(dir),
    path: dir.path,
    children: sortedChildren(scan, dir.path).map((e) =>
      e.kind === "doc" ? docTopic(e) : dirTopic(e),
    ),
  });

  const sections: Section[] = [];
  for (const entry of sortedChildren(scan, "")) {
    if (entry.kind === "doc") {
      sections.push({
        id: newId(),
        title: docLabel(entry),
        path: entry.path,
        isOrphan: true,
        topics: [docTopic(entry)],
      });
      continue;
    }
    const node = dirTopic(entry);
    if (node.children.length === 0) {
      // dir whose only visible doc is its absorbed index → leaf card
      sections.push({
        id: newId(),
        title: node.title,
        path: entry.path,
        isOrphan: true,
        topics: [node],
      });
    } else {
      sections.push({
        id: newId(),
        title: node.title,
        path: entry.path,
        topics: node.children,
      });
    }
  }

  return {
    doc: {
      id: newId(),
      name: rootName,
      formatId: DOCUSAURUS_FORMAT_ID,
      // Keep the nav, not the file (docs/15).
      extras: {
        files: toNavHeads(files),
        // Harvested HERE, where whole bodies are still in hand —
        // `toNavHeads` is applied on the line above, inside this same
        // function. Stamped by the loader; `parse` reads no clock.
        linkIndex: buildLinkIndex({
          bodies: Object.entries(files).filter(([path]) => DOC_RE.test(path)),
          species: docusaurusLinkSpecies(
            Object.keys(files).filter((path) => DOC_RE.test(path)),
          ),
          observedAt: UNSTAMPED,
        }) satisfies LinkIndex,
      },
      sections,
    },
    warnings: scan.warnings,
  };
}

// ── Links, harvested once at import (docs/16 step 7) ────────
/**
 * A doc's ID — what another sidebar refers to it by.
 *
 * NOT the route: the id keeps the docs-root-relative path without the
 * extension and WITHOUT the leading slash, and a numeric prefix is
 * stripped the same way. Kept as its own function beside `routeOf`
 * because the two are one character apart and mean different things —
 * exactly the pair this note keeps splitting.
 */
function docIdOf(path: string): string {
  return routeOf(path).replace(/^\//, "");
}

/**
 * A doc's route, Docusaurus's default derivation.
 *
 * `docs/guides/intro.md` -> `/docs/guides/intro`. The extension goes, a
 * numeric prefix goes (`01-intro.md` publishes as `intro`), and an
 * index-like file addresses its own directory.
 *
 * THE SECOND URL DERIVATION. Hugo strips a content root and appends a
 * trailing slash; this strips a numeric prefix and does not. The harvest
 * loop is identical for both, which is the whole claim of a shared
 * harvester — and a claim like that is only proved by a second producer.
 */
function routeOf(path: string): string {
  const withoutExt = path.replace(/\.(md|mdx)$/i, "");
  const segments = withoutExt.split("/").filter(Boolean);
  const last = segments[segments.length - 1] ?? "";
  if (/^(index|readme)$/i.test(last)) segments.pop();
  return "/" + segments.map((seg) => seg.replace(/^\d+-/, "")).join("/");
}

/**
 * The two species a Docusaurus move affects, counted together and named
 * separately.
 *
 * Relative markdown links are the DOMINANT hand-authored species here,
 * and the inverse of Hugo — that corpus had zero of them against 5,796
 * absolute site paths. Both break silently when a file moves, and
 * neither is repairable the way Hugo's are, because Docusaurus has no
 * alias key to write into front matter.
 *
 * DOC IDS ARE NOT A SPECIES HERE, deliberately. A doc id is not a link
 * and does not resolve to one: it is a handle another sidebar refers to,
 * and a move changes it without touching any link at all. It stays in
 * the WARNING, which NAMES it, while this COUNTS urls — two facts that
 * break differently and are fixed differently, so they keep two
 * channels (docs/16).
 */
function docusaurusLinkSpecies(paths: readonly string[]): LinkSpecies[] {
  const byRoute = new Map<string, string>();
  const byPath = new Map<string, string>();
  for (const path of paths) {
    byRoute.set(routeOf(path), path);
    byPath.set(path, path);
  }

  /** Resolve `./x.md` or `../y/z.md` against the linking file's dir. */
  const relative = (raw: string, fromPath: string): string | null => {
    const clean = raw.split("#")[0]!.split("?")[0]!;
    if (clean === "" || clean.startsWith("/")) return null;
    const base = fromPath.slice(0, fromPath.lastIndexOf("/"));
    const out: string[] = base.split("/").filter(Boolean);
    for (const seg of clean.split("/")) {
      if (seg === "" || seg === ".") continue;
      if (seg === "..") out.pop();
      else out.push(seg);
    }
    return byPath.get(out.join("/")) ?? null;
  };

  return [
    {
      name: "relative-markdown",
      find: (body) => [...body.matchAll(/\]\((\.[^)\s]*\.mdx?)\)/gi)].map((m) => m[1]!),
      resolve: relative,
    },
    {
      name: "absolute-route",
      find: (body) => [...body.matchAll(/\]\((\/[^)\s]*)\)/g)].map((m) => m[1]!),
      resolve: (raw) => {
        const clean = raw.split("#")[0]!.split("?")[0]!.replace(/\/$/, "");
        return byRoute.get(clean) ?? null;
      },
    },
  ];
}

// ── planChanges ─────────────────────────────────────────────

interface Placed {
  node: TargetNode;
  kind: "doc" | "dir";
  /** doc → final file path; dir → final directory path. */
  finalPath: string;
  doc?: DocEntry; // backing doc (leaf, or conversion index source)
  dir?: DirEntry; // backing dir
  parent: Placed | null;
  created: boolean;
  /** Doc that gained children → becomes <name>/index.<ext>. */
  converted: boolean;
}

function planChanges(
  files: FilesSnapshot,
  doc: TocDocument,
  sectionOrder: string[],
): CollectionPlanResult {
  const warnings: CollectionWarning[] = [];
  const scan = scanFiles(files);
  const targetRoots = targetFromModel(doc, sectionOrder);

  // ── placement: assign every target node a filesystem location ──
  const placed: Placed[] = [];
  const placedOriginals = new Set<string>();
  const usedNamesByDir = new Map<string, Set<string>>();
  const claimName = (dir: string, want: string, ext = ""): string => {
    let names = usedNamesByDir.get(dir);
    if (!names) {
      names = new Set();
      usedNamesByDir.set(dir, names);
    }
    let name = want + ext;
    let n = 2;
    while (names.has(name.toLowerCase())) name = `${want}-${n++}${ext}`;
    names.add(name.toLowerCase());
    return name;
  };
  // excluded docs stay in place — reserve their names so stubs/moves
  // don't try to claim them (final collision check is the backstop)
  for (const d of scan.docs.values()) {
    if (d.excluded) claimName(d.parentDir, d.base, d.ext);
  }

  const place = (node: TargetNode, parent: Placed | null, parentDir: string): void => {
    const backing =
      node.path !== null && !placedOriginals.has(node.path) ? node.path : null;
    const docEntry = backing !== null ? scan.docs.get(backing) : undefined;
    const dirEntry = backing !== null && !docEntry ? scan.dirs.get(backing) : undefined;
    if (docEntry || dirEntry) placedOriginals.add(backing!);

    if (dirEntry) {
      const finalPath = join(parentDir, claimName(parentDir, dirEntry.base));
      const p: Placed = {
        node,
        kind: "dir",
        finalPath,
        dir: dirEntry,
        parent,
        created: false,
        converted: false,
      };
      placed.push(p);
      for (const child of node.children) place(child, p, finalPath);
    } else if (docEntry && node.children.length > 0) {
      // a doc gained children → convert to a category-with-index
      const finalPath = join(parentDir, claimName(parentDir, docEntry.base));
      const p: Placed = {
        node,
        kind: "dir",
        finalPath,
        doc: docEntry,
        parent,
        created: false,
        converted: true,
      };
      placed.push(p);
      for (const child of node.children) place(child, p, finalPath);
    } else if (docEntry) {
      placed.push({
        node,
        kind: "doc",
        finalPath: join(parentDir, claimName(parentDir, docEntry.base, docEntry.ext)),
        doc: docEntry,
        parent,
        created: false,
        converted: false,
      });
    } else if (node.children.length > 0) {
      const finalPath = join(parentDir, claimName(parentDir, slugify(node.title)));
      const p: Placed = {
        node,
        kind: "dir",
        finalPath,
        parent,
        created: true,
        converted: false,
      };
      placed.push(p);
      for (const child of node.children) place(child, p, finalPath);
    } else {
      placed.push({
        node,
        kind: "doc",
        finalPath: join(parentDir, claimName(parentDir, slugify(node.title), ".md")),
        parent,
        created: true,
        converted: false,
      });
    }
  };
  for (const root of targetRoots) place(root, null, "");

  // dir relocations (identity included — longest-prefix remap for
  // files the model doesn't track: excluded docs, unplaced categories)
  const dirMoves = placed
    .filter((p) => p.kind === "dir" && p.dir)
    .map((p) => ({ from: p.dir!.path, to: p.finalPath }))
    .sort((a, b) => b.from.length - a.from.length);
  const remap = (path: string): string => {
    for (const { from, to } of dirMoves) {
      if (path.startsWith(from + "/")) return to + path.slice(from.length);
    }
    return path;
  };

  // ── accumulated edits ─────────────────────────────────────
  const fmEdits = new Map<string, FrontmatterEdits>(); // by ORIGINAL path
  const fmEditFor = (path: string): FrontmatterEdits => {
    let e = fmEdits.get(path);
    if (!e) {
      e = { set: {}, remove: [] };
      fmEdits.set(path, e);
    }
    return e;
  };
  const catEdits = new Map<Placed, Record<string, string | number>>();
  const catSet = (p: Placed, key: string, value: string | number): void => {
    if (p.dir?.category?.[key] === value) return;
    let m = catEdits.get(p);
    if (!m) {
      m = {};
      catEdits.set(p, m);
    }
    m[key] = value;
  };

  // ── labels ────────────────────────────────────────────────
  for (const p of placed) {
    if (p.created) {
      if (p.kind === "dir") catSet(p, "label", p.node.title);
      continue; // created docs carry `title:` in their stub
    }
    const finalBase = baseOf(p.finalPath).replace(DOC_RE, "");
    if (p.kind === "doc") {
      const d = p.doc!;
      const effective = d.sidebarLabel ?? d.title ?? finalBase;
      if (effective !== p.node.title) {
        if (d.title === p.node.title && d.hasLabelKey) {
          fmEditFor(d.path).remove!.push("sidebar_label");
        } else {
          fmEditFor(d.path).set!.sidebar_label = p.node.title;
        }
      }
    } else if (p.converted) {
      const d = p.doc!;
      // after conversion the dir's label = category ?? index label ?? dir name
      const effective = d.sidebarLabel ?? d.title ?? finalBase;
      if (effective !== p.node.title) catSet(p, "label", p.node.title);
    } else {
      const dir = p.dir!;
      const catLabel =
        typeof dir.category?.label === "string" ? dir.category.label : undefined;
      const effective =
        catLabel ?? dir.index?.sidebarLabel ?? dir.index?.title ?? finalBase;
      if (effective !== p.node.title) catSet(p, "label", p.node.title);
    }
  }

  // ── positions per sibling group ───────────────────────────
  const createdPositions = new Map<Placed, number>();
  const groups: Placed[][] = [placed.filter((p) => p.parent === null)];
  for (const p of placed) {
    const kids = placed.filter((q) => q.parent === p);
    if (kids.length > 0) groups.push(kids);
  }
  for (const group of groups) {
    const current = (p: Placed): number | undefined => {
      if (p.created) return undefined;
      if (p.kind === "doc" || p.converted) return p.doc!.position;
      return dirPosition(p.dir!);
    };
    const key = (p: Placed): OrderKey => ({
      position: current(p),
      base: baseOf(p.finalPath).replace(DOC_RE, ""),
      path: p.finalPath,
    });
    const induced = [...group].sort((a, b) => compareOrder(key(a), key(b)));
    if (induced.every((p, i) => p === group[i])) continue;

    group.forEach((p, i) => {
      const target = i + 1;
      if (p.created) {
        if (p.kind === "doc") createdPositions.set(p, target);
        else catSet(p, "position", target);
        return;
      }
      if (p.kind === "doc") {
        if (p.doc!.position !== target) {
          fmEditFor(p.doc!.path).set!.sidebar_position = target;
        }
        return;
      }
      // dirs (incl. conversions): category `position` is authoritative
      if (current(p) !== target) catSet(p, "position", target);
      // keep a stale index/converted-doc sidebar_position in sync
      const idx = p.converted ? p.doc! : p.dir!.index;
      if (idx?.hasPositionKey && idx.position !== target) {
        fmEditFor(idx.path).set!.sidebar_position = target;
      }
    });
  }

  // ── removals → unlisted: true ─────────────────────────────
  const absorbedOfPlaced = new Set<string>();
  for (const p of placed) {
    if (p.kind === "dir" && p.dir?.index) absorbedOfPlaced.add(p.dir.index.path);
  }
  let unlistedCount = 0;
  for (const d of scan.docs.values()) {
    if (d.excluded || placedOriginals.has(d.path) || absorbedOfPlaced.has(d.path)) {
      continue;
    }
    fmEditFor(d.path).set!.unlisted = true;
    unlistedCount++;
  }
  if (unlistedCount > 0) {
    warnings.push({
      kind: "unlisted-removal",
      detail: `${unlistedCount} page(s) hidden via "unlisted: true" (needs Docusaurus 3+) — files are never deleted`,
    });
  }

  // ── materialize ───────────────────────────────────────────
  const changes: FileChange[] = [];

  // final location of every model-tracked original file
  const finalLoc = new Map<string, string>();
  for (const p of placed) {
    if (p.kind === "doc" && p.doc) finalLoc.set(p.doc.path, p.finalPath);
    if (p.kind === "dir" && p.converted && p.doc) {
      finalLoc.set(p.doc.path, join(p.finalPath, `index${p.doc.ext}`));
    }
    if (p.kind === "dir" && p.dir?.index) {
      finalLoc.set(p.dir.index.path, join(p.finalPath, baseOf(p.dir.index.path)));
    }
  }

  // category json edits/creates
  const catFinalLoc = new Map<string, string>();
  const catNewContent = new Map<string, string>();
  for (const p of placed) {
    if (p.kind !== "dir") continue;
    const edits = catEdits.get(p);
    const origPath = p.dir?.categoryPath;
    if (origPath !== undefined) {
      // the file keeps its own name (yml stays yml) at the final dir
      catFinalLoc.set(origPath, join(p.finalPath, baseOf(origPath)));
      if (edits && Object.keys(edits).length > 0) {
        if (p.dir!.categoryBroken) {
          warnings.push({
            kind: "broken-category",
            blocking: true,
            detail: `${origPath}: cannot edit an unparsable category file — fix it by hand first`,
          });
        } else if (p.dir!.categoryKind === "yml") {
          // byte-preserving line surgery — nested keys/comments survive
          const { content, refused } = applyYamlFileEdits(files[origPath]!, {
            set: edits,
          });
          for (const key of refused) {
            warnings.push({
              kind: "unmergeable-frontmatter",
              blocking: true,
              detail: `${origPath}: "${key}" uses YAML syntax the planner won't rewrite — edit by hand`,
            });
          }
          if (content !== files[origPath]) catNewContent.set(origPath, content);
        } else {
          catNewContent.set(
            origPath,
            JSON.stringify({ ...(p.dir!.category ?? {}), ...edits }, null, 2) + "\n",
          );
        }
      }
    } else if (edits && Object.keys(edits).length > 0) {
      changes.push({
        kind: "create",
        path: join(p.finalPath, CATEGORY),
        newContent: JSON.stringify(edits, null, 2) + "\n",
      });
    }
  }

  // sweep every original file: apply edits, emit moves/edits
  for (const path of Object.keys(files).sort()) {
    const isCategory = CATEGORY_RE.test(baseOf(path));
    if (!isCategory && !DOC_RE.test(path)) continue;
    let loc: string;
    let newContent = files[path]!;
    if (isCategory) {
      loc = catFinalLoc.get(path) ?? remap(path);
      newContent = catNewContent.get(path) ?? newContent;
    } else {
      loc = finalLoc.get(path) ?? remap(path);
      const edits = fmEdits.get(path);
      if (edits) {
        const result = editDocFrontmatter(files[path]!, edits);
        for (const key of result.refused) {
          warnings.push({
            kind: "unmergeable-frontmatter",
            blocking: true,
            detail: `${path}: "${key}" uses YAML syntax the planner won't rewrite — edit by hand`,
          });
        }
        newContent = result.content;
      }
    }
    // Docs carry their nav in front matter, so a change ships the NAV
    // HEAD and the body stays on disk (docs/15). `_category_` files ARE
    // the nav in full, so they stay whole-file writes.
    const region = isCategory ? undefined : ("navHead" as const);
    const payload = isCategory ? newContent : navHeadOf(newContent);
    if (loc !== path) {
      changes.push({
        kind: "move",
        fromPath: path,
        toPath: loc,
        newContent: payload,
        region,
      });
    } else if (newContent !== files[path]) {
      changes.push({ kind: "edit", path, newContent: payload, region });
    }
  }

  // creates: doc stubs + index stubs for dirs that would vanish
  for (const p of placed) {
    if (p.created && p.kind === "doc") {
      const kv: Record<string, string | number> = { title: p.node.title };
      const pos = createdPositions.get(p);
      if (pos !== undefined) kv.sidebar_position = pos;
      const lines = Object.entries(kv).map(([k, v]) => `${k}: ${dumpScalar(v)}`);
      changes.push({
        kind: "create",
        path: p.finalPath,
        newContent: `---\n${lines.join("\n")}\n---\n\n# ${p.node.title}\n`,
      });
      warnings.push({
        kind: "stub-created",
        detail: `${p.finalPath}: new page stub for "${p.node.title}" (add real content)`,
      });
    }
    if (p.kind === "dir" && !p.converted && !p.dir?.index) {
      const hasChildren = placed.some((q) => q.parent === p);
      if (!hasChildren) {
        // a category with no visible docs disappears from the sidebar —
        // give the childless dir an index stub so it survives
        changes.push({
          kind: "create",
          path: join(p.finalPath, "index.md"),
          newContent: `---\ntitle: ${dumpScalar(p.node.title)}\n---\n\n# ${p.node.title}\n`,
        });
      }
    }
  }

  // TWO SPECIES, TWO CHANNELS (docs/16 step 7).
  //
  // The generic "links may break" fired on every move and carried no
  // information — the wallpaper failure docs/17 was redesigned to avoid.
  // It becomes specific by COUNTING urls from the shared index, while
  // doc ids keep being NAMED rather than counted.
  //
  // They are not the same fact and must not merge: a doc id is a handle
  // another sidebar refers to, changed by the move without any link
  // being touched, and no redirect can repair it. Counting them together
  // would produce one number that means neither thing.
  const moved = changes.filter(
    (c): c is Extract<FileChange, { kind: "move" }> => c.kind === "move",
  );
  if (moved.length > 0) {
    const index = (doc.extras as { linkIndex?: LinkIndex } | undefined)?.linkIndex;
    let inbound = 0;
    let measured = false;
    for (const change of moved) {
      const n = inboundCount(index, change.fromPath);
      if (n === null) continue;
      measured = true;
      inbound += n;
    }
    warnings.push({
      kind: "links-may-break",
      // Absent, not zero, when nothing was measured: an index-less
      // document is unmeasured, and "0 inbound links" would be a number
      // lying by omission.
      detail: measured
        ? `${moved.length} file(s) will move · ${inbound} inbound link${inbound === 1 ? "" : "s"} point at them, as of import — not rewritten`
        : `${moved.length} file(s) will move — relative links are not rewritten`,
    });
    // The OTHER species, named and never counted into the number above.
    warnings.push({
      kind: "doc-ids-change",
      detail: `${moved.length} doc ID${moved.length === 1 ? "" : "s"} change with ${moved.length === 1 ? "this move" : "these moves"}: ${moved
        .slice(0, 5)
        .map((c) => `${docIdOf(c.fromPath)} → ${docIdOf(c.toPath)}`)
        .join(
          ", ",
        )}${moved.length > 5 ? `, +${moved.length - 5} more` : ""}. Anything referring to a doc by ID — another sidebar, a DocCardList — follows the new one.`,
    });
  }

  // collision backstop: no two writes to one path; never clobber a
  // file the plan doesn't vacate
  const vacated = new Set(
    changes.filter((c) => c.kind === "move").map((c) => c.fromPath),
  );
  const written = new Set<string>();
  for (const c of changes) {
    const to = c.kind === "move" ? c.toPath : c.path;
    const clobbers = c.kind !== "edit" && files[to] !== undefined && !vacated.has(to);
    if (written.has(to) || clobbers) {
      warnings.push({
        kind: "path-collision",
        blocking: true,
        detail: `${to}: two files would end up at the same path — rename one first`,
      });
    }
    written.add(to);
  }

  return { changes, warnings };
}

/** Frontmatter surgery that can also CREATE a block — Docusaurus docs
 *  commonly have none, and a first sidebar_label/unlisted needs one. */
function editDocFrontmatter(
  content: string,
  edits: FrontmatterEdits,
): { content: string; refused: string[] } {
  if (parseFrontmatter(content)) return applyFrontmatterEdits(content, edits);
  const set = edits.set ?? {};
  if (Object.keys(set).length === 0) return { content, refused: [] };
  const eol = content.includes("\r\n") ? "\r\n" : "\n";
  const lines = Object.entries(set).map(([k, v]) => `${k}: ${dumpScalar(v)}`);
  return {
    content: `---${eol}${lines.join(eol)}${eol}---${eol}${content}`,
    refused: [],
  };
}

// ── Adapter ─────────────────────────────────────────────────

export const docusaurusAdapter: CollectionAdapter = {
  id: DOCUSAURUS_FORMAT_ID,
  // Autogenerated sidebars read the directory tree, so a parent change
  // emits FileChange.move — it has since docs/11.
  reparentMovesFiles: true,
  // Both true: a new top-level card is created either way it can exist —
  // a directory with a fresh `_category_.json` carrying its label, or a
  // doc stub — and the root group's order is written as
  // `sidebar_position` / category `position`.
  createCards: true,
  reorderCards: true,
  // An autogenerated category comes from a directory and may carry only
  // `_category_.json` — a label and a position, no doc. Pageless nodes
  // are ordinary here.
  nodesNeedTargets: false,
  /**
   * BOTH. An autogenerated sidebar maps the filesystem directly: a doc
   * file at the docs root becomes a top-level `doc` item, a folder
   * becomes a `category`. This adapter's own parse mints the first as a
   * standalone already.
   *
   * METHOD — published-rendering fidelity, from the format's published
   * nav contract: docusaurus.io/docs/sidebar/autogenerated states "each
   * folder creates a sidebar category, and each file creates a doc
   * link", and its worked example shows a root-level `intro.md` becoming
   * the bare item `'intro'` beside `type: 'category'` entries for the
   * folders. (Retrieved 2026-08-21.)
   *
   * VERIFIED AGAINST THIS PLANNER: hoisting `guides/installation.md` to
   * a standalone at root plans the move to `installation.md` and warns
   * that the doc ID changes `guides/installation → installation` — no
   * category is created. The WRAP shape additionally plans
   * `create <slug>/_category_.json` and moves the page inside it. Both
   * writable; the standalone is the shape the contract above describes.
   */
  rootBearing: { sections: true, orphans: true },
  label: "Docusaurus (autogenerated sidebar)",
  ingests: (path) => DOC_RE.test(path) || CATEGORY_RE.test(baseOf(path)),
  detect: (files) => {
    const paths = Object.keys(files);
    if (paths.some((p) => CATEGORY_RE.test(baseOf(p)))) return 0.9;
    const mdPaths = paths.filter((p) => DOC_RE.test(p));
    if (mdPaths.length === 0) return 0;
    let sidebarish = 0;
    for (const p of mdPaths) {
      const data = parseFrontmatter(files[p]!)?.data;
      if (data?.sidebar_position !== undefined || data?.sidebar_label !== undefined) {
        sidebarish++;
      }
    }
    return sidebarish >= Math.max(2, mdPaths.length * 0.3) ? 0.75 : 0;
  },
  parse,
  planChanges,
};
