/**
 * Docusaurus adapter conformance against a synthetic autogenerated
 * docs tree (categories, _category_.json, category-index absorption,
 * mdx, unlisted), plus the round-trip laws:
 *   no edits → [] · minimal touch · sidebar_label renames ·
 *   _category_.json label/position surgery · cross-folder moves ·
 *   doc→category conversion · unlisted removals · idempotency ·
 *   verification-by-simulation.
 */

import { describe, expect, it } from "vitest";
import { deriveSectionOrder, initialColumns } from "@/layout/columns";
import { runCommand } from "@/commands/dispatcher";
import type { Command, EditorState } from "@/commands/types";
import type { TocDocument } from "@/model/types";
import { docusaurusAdapter } from "../adapters/docusaurus";
import { navHeadOf, spliceNavHead } from "../navHead";
import { applyChanges, simulatePlan } from "../verify";
import type { FileChange, FilesSnapshot } from "../types";

// ── Load fixtures as a FilesSnapshot ────────────────────────

const raw = import.meta.glob("./fixtures/docusaurus/**/*.{md,mdx,json}", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

function snapshot(): FilesSnapshot {
  const files: FilesSnapshot = {};
  for (const [key, content] of Object.entries(raw)) {
    files[key.replace("./fixtures/docusaurus/", "")] = content;
  }
  return files;
}

function parseFixture() {
  return docusaurusAdapter.parse(snapshot(), "Docs Site");
}

function findTopic(doc: TocDocument, title: string): { sectionId: string; id: string } {
  for (const s of doc.sections) {
    const stack = [...s.topics];
    while (stack.length) {
      const t = stack.pop()!;
      if (t.title === title) return { sectionId: s.id, id: t.id };
      stack.push(...t.children);
    }
  }
  throw new Error(`topic ${title} not found`);
}

function section(doc: TocDocument, title: string) {
  const s = doc.sections.find((x) => x.title === title);
  if (!s) throw new Error(`section ${title} not found`);
  return s;
}

function edit(doc: TocDocument, command: Command): EditorState {
  const state: EditorState = {
    document: doc,
    columns: initialColumns(doc),
    view: { globalDepth: 2, cardDepths: {} },
  };
  const { next, entry } = runCommand(state, command);
  expect(entry, `expected ${command.type} to change state`).not.toBeNull();
  return next;
}

function plan(files: FilesSnapshot, state: EditorState) {
  return docusaurusAdapter.planChanges!(
    files,
    state.document,
    deriveSectionOrder(state.columns),
  );
}

// ── parse ───────────────────────────────────────────────────

describe("docusaurus parse", () => {
  it("assembles the directory tree with positions then names", () => {
    const { doc } = parseFixture();
    expect(doc.formatId).toBe("docusaurus");
    // positioned: intro (1), Guides (2); then alphabetical by name:
    // changelog, faq, reference
    expect(doc.sections.map((s) => s.title)).toEqual([
      "Introduction",
      "Guides",
      "Changelog",
      "FAQ",
      "Reference",
    ]);
    const guides = section(doc, "Guides");
    // sidebar_label beats title; category label from _category_.json
    expect(guides.topics.map((t) => t.title)).toEqual([
      "Installation",
      "Configuring",
      "Advanced use",
    ]);
    // no positions → alphabetical by file name (scaling < tuning)
    expect(guides.topics[2]!.children.map((t) => t.title)).toEqual([
      "Scaling out",
      "Performance tuning",
    ]);
  });

  it("keeps underscore partials out of the nav — and never unlists them", () => {
    const files: FilesSnapshot = {
      ...snapshot(),
      "guides/_partial-note.mdx": "---\ntitle: Partial\n---\nShared fragment\n",
    };
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    expect(JSON.stringify(doc.sections)).not.toContain("_partial-note");

    // removing a section must not touch the partial either
    const state = edit(doc, {
      type: "removeSection",
      sectionId: section(doc, "Guides").id,
    });
    const { changes } = docusaurusAdapter.planChanges!(
      files,
      state.document,
      deriveSectionOrder(state.columns),
    );
    expect(
      changes.some((c) => (c.kind === "move" ? c.toPath : c.path).includes("_partial")),
    ).toBe(false);
  });

  it("absorbs category indexes and honors unlisted", () => {
    const { doc } = parseFixture();
    // reference/index.md absorbed: labels the category, not a child
    const ref = section(doc, "Reference");
    expect(ref.topics.map((t) => t.title)).toEqual(["CLI", "API"]);
    expect(ref.path).toBe("reference");
    // dir whose only doc is its index → leaf orphan card
    const faq = section(doc, "FAQ");
    expect(faq.isOrphan).toBe(true);
    expect(faq.topics[0]!.path).toBe("faq");
    // unlisted page absent entirely
    expect(JSON.stringify(doc.sections)).not.toContain("Hidden page");
  });

  it("detects the collection", () => {
    expect(docusaurusAdapter.detect(snapshot())).toBeGreaterThan(0.5);
    expect(docusaurusAdapter.detect({ "a.md": "# no sidebar metadata\n" })).toBe(0);
  });
});

// ── the laws ────────────────────────────────────────────────

describe("docusaurus round-trip laws", () => {
  it("LAW: no model edits → zero changes", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const state: EditorState = {
      document: doc,
      columns: initialColumns(doc),
      view: { globalDepth: 2, cardDepths: {} },
    };
    expect(plan(files, state).changes).toEqual([]);
  });

  it("a reorder renumbers ONLY the group, only position lines", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const guides = section(doc, "Guides");
    // move Configuring to the front of Guides
    const configuring = findTopic(doc, "Configuring");
    const state = edit(doc, {
      type: "moveTopics",
      topicIds: [configuring.id],
      toSectionId: guides.id,
      toParentTopicId: null,
      toIndex: 0,
    });

    const { changes, warnings } = plan(files, state);
    expect(warnings.filter((w) => w.blocking)).toEqual([]);
    // Advanced use keeps position 3 (already correct) — only the two
    // swapped docs are touched
    const paths = changes.map((c) => (c.kind === "move" ? c.toPath : c.path)).sort();
    expect(paths).toEqual(["guides/configuration.mdx", "guides/installation.md"]);
    for (const change of changes) {
      if (change.kind !== "edit") continue;
      // Head-to-head: a plan carries the nav head, so diffing it against
      // the whole file would only measure the body it omits by design.
      expect(change.region).toBe("navHead");
      const before = navHeadOf(files[change.path]!).split("\n");
      const after = change.newContent.split("\n");
      expect(after.length).toBe(before.length);
      const diffs = before.filter((line, i) => after[i] !== line);
      for (const line of diffs) expect(line).toMatch(/^sidebar_position[ \t]*:/);
    }
  });

  it("renaming a doc sets sidebar_label; renaming a category edits _category_.json", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const installation = findTopic(doc, "Installation");
    let state = edit(doc, {
      type: "renameTopic",
      sectionId: installation.sectionId,
      topicId: installation.id,
      title: "Install",
    });
    state = edit(state.document, {
      type: "renameSection",
      sectionId: section(state.document, "Guides").id,
      title: "How-to guides",
    });

    const { changes } = plan(files, state);
    const byPath = new Map(
      changes.map((c) => [c.kind === "move" ? c.toPath : c.path, c]),
    );
    expect(
      (byPath.get("guides/installation.md") as { newContent: string }).newContent,
    ).toContain("sidebar_label: Install");
    const cat = JSON.parse(
      (byPath.get("guides/_category_.json") as { newContent: string }).newContent,
    ) as Record<string, unknown>;
    expect(cat.label).toBe("How-to guides");
    expect(cat.collapsed).toBe(false); // unmanaged keys preserved
    expect(cat.position).toBe(2);
    expect(byPath.size).toBe(2); // nothing else touched
  });

  it("a cross-folder move is a rename-style FileChange plus a links warning", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const api = findTopic(doc, "API");
    const state = edit(doc, {
      type: "moveTopics",
      topicIds: [api.id],
      toSectionId: section(doc, "Guides").id,
      toParentTopicId: null,
      toIndex: 3,
    });

    const { changes, warnings } = plan(files, state);
    expect(changes).toEqual([
      {
        kind: "move",
        fromPath: "reference/api.md",
        toPath: "guides/api.md",
        // The page moves with its front matter unchanged; the body is not
        // in the plan at all, and rides along via splice-on-save.
        newContent: navHeadOf(files["reference/api.md"]!),
        region: "navHead",
      },
    ]);
    expect(warnings.some((w) => w.kind === "links-may-break")).toBe(true);
    const sim = simulatePlan(
      docusaurusAdapter,
      files,
      state.document,
      deriveSectionOrder(state.columns),
      changes,
    );
    expect(sim.ok).toBe(true);
  });

  it("moving a whole category moves its _category_.json and every doc", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const advanced = findTopic(doc, "Advanced use");
    const state = edit(doc, {
      type: "moveTopics",
      topicIds: [advanced.id],
      toSectionId: section(doc, "Reference").id,
      toParentTopicId: null,
      toIndex: 2,
    });

    const { changes, warnings } = plan(files, state);
    expect(warnings.filter((w) => w.blocking)).toEqual([]);
    const moves = changes.filter((c) => c.kind === "move");
    expect(moves.map((m) => `${m.fromPath} -> ${m.toPath}`).sort()).toEqual([
      "guides/advanced/_category_.json -> reference/advanced/_category_.json",
      "guides/advanced/scaling.md -> reference/advanced/scaling.md",
      "guides/advanced/tuning.md -> reference/advanced/tuning.md",
    ]);
    const sim = simulatePlan(
      docusaurusAdapter,
      files,
      state.document,
      deriveSectionOrder(state.columns),
      changes,
    );
    expect(sim.ok).toBe(true);
  });

  it("a doc that gains children converts to a category with an index", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const tuning = findTopic(doc, "Performance tuning");
    const installation = findTopic(doc, "Installation");
    const state = edit(doc, {
      type: "moveTopics",
      topicIds: [tuning.id],
      toSectionId: installation.sectionId,
      toParentTopicId: installation.id,
      toIndex: 0,
    });

    const { changes, warnings } = plan(files, state);
    expect(warnings.filter((w) => w.blocking)).toEqual([]);
    const moves = changes
      .filter((c) => c.kind === "move")
      .map((m) => `${m.fromPath} -> ${m.toPath}`)
      .sort();
    expect(moves).toEqual([
      "guides/advanced/tuning.md -> guides/installation/tuning.md",
      "guides/installation.md -> guides/installation/index.md",
    ]);
    const sim = simulatePlan(
      docusaurusAdapter,
      files,
      state.document,
      deriveSectionOrder(state.columns),
      changes,
    );
    expect(sim.ok).toBe(true);
  });

  it("removing a section unlists every doc in it (files never deleted)", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const state = edit(doc, {
      type: "removeSection",
      sectionId: section(doc, "Reference").id,
    });

    const { changes, warnings } = plan(files, state);
    const edited = changes.filter((c) => c.kind === "edit");
    expect(edited.map((c) => c.path).sort()).toEqual([
      "reference/api.md",
      "reference/cli.md",
      "reference/index.md",
    ]);
    for (const c of edited) expect(c.newContent).toContain("unlisted: true");
    expect(warnings.some((w) => w.kind === "unlisted-removal")).toBe(true);
  });

  it("a new in-app grouping creates a directory with _category_.json", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");
    const doc2 = structuredClone(doc);
    const guides = doc2.sections.find((s) => s.title === "Guides")!;
    const moved = guides.topics.pop()!; // Advanced use subtree
    doc2.sections.push({
      id: "new-group",
      title: "Brand New Group",
      topics: [moved],
    } as never);
    const order = [...initialColumns(doc2).flat()];
    const { changes, warnings } = docusaurusAdapter.planChanges!(files, doc2, order);
    expect(warnings.filter((w) => w.blocking)).toEqual([]);
    const create = changes.find(
      (c) => c.kind === "create" && c.path === "brand-new-group/_category_.json",
    );
    expect(create).toBeDefined();
    expect(create!.newContent).toContain("Brand New Group");
    // the subtree physically moves inside the new directory
    expect(
      changes.some(
        (c) => c.kind === "move" && c.toPath === "brand-new-group/advanced/tuning.md",
      ),
    ).toBe(true);
  });

  it("LAW: idempotency + simulation for a compound editing session", () => {
    const files = snapshot();
    const { doc } = docusaurusAdapter.parse(files, "Docs Site");

    let state: EditorState = {
      document: doc,
      columns: initialColumns(doc),
      view: { globalDepth: 2, cardDepths: {} },
    };
    const apply = (cmd: Command) => {
      const { next, entry } = runCommand(state, cmd);
      expect(entry).not.toBeNull();
      state = next;
    };
    apply({
      type: "renameSection",
      sectionId: section(state.document, "Guides").id,
      title: "Handbook",
    });
    apply({
      type: "moveTopics",
      topicIds: [findTopic(state.document, "API").id],
      toSectionId: section(state.document, "Handbook").id,
      toParentTopicId: null,
      toIndex: 0,
    });
    apply({
      type: "moveTopics",
      topicIds: [findTopic(state.document, "Scaling out").id],
      toSectionId: section(state.document, "Reference").id,
      toParentTopicId: null,
      toIndex: 0,
    });

    const order = deriveSectionOrder(state.columns);
    const { changes, warnings } = docusaurusAdapter.planChanges!(
      files,
      state.document,
      order,
    );
    expect(warnings.filter((w) => w.blocking)).toEqual([]);

    const sim = simulatePlan(docusaurusAdapter, files, state.document, order, changes);
    expect(sim.ok).toBe(true);

    const patched = applyChanges(files, changes);
    const reparsed = docusaurusAdapter.parse(patched, "Docs Site");
    const again = docusaurusAdapter.planChanges!(
      patched,
      reparsed.doc,
      deriveSectionOrder(initialColumns(reparsed.doc)),
    );
    expect(again.changes).toEqual([]);
  });
});

describe("heading-derived titles (docs with no frontmatter title)", () => {
  const FILES: FilesSnapshot = {
    "cli.mdx":
      "---\nsidebar_position: 2\n---\n\n" +
      "```bash\n# not a heading — fenced comment\n```\n\n" +
      "# CLI Reference {#cli}\n\nUsage.\n",
    "guide/index.md": "# The Guide\n\nNo frontmatter at all.\n",
    "guide/setup.md": "---\nsidebar_position: 1\n---\n\n# Setting Up ##\n\nText.\n",
    "guide/bare.md": "No frontmatter, no heading either.\n",
  };

  it("labels fall back to the first # heading, then the filename", () => {
    const { doc } = docusaurusAdapter.parse(FILES, "Site");
    // fenced "# comment" skipped; {#anchor} and trailing hashes stripped
    expect(doc.sections.map((s) => s.title)).toEqual(["CLI Reference", "The Guide"]);
    const guide = section(doc, "The Guide"); // absorbed index heading names the dir
    expect(guide.topics.map((t) => t.title)).toEqual(["Setting Up", "bare"]);
  });

  it("LAW: heading-derived labels are stable — no-op plans stay empty", () => {
    const { doc } = docusaurusAdapter.parse(FILES, "Site");
    expect(
      docusaurusAdapter.planChanges!(FILES, doc, deriveSectionOrder(initialColumns(doc)))
        .changes,
    ).toEqual([]);
  });

  it("renaming writes sidebar_label — the heading is never touched", () => {
    const { doc } = docusaurusAdapter.parse(FILES, "Site");
    const setup = findTopic(doc, "Setting Up");
    const state = edit(doc, {
      type: "renameTopic",
      sectionId: setup.sectionId,
      topicId: setup.id,
      title: "Setup",
    });
    const { changes } = plan(FILES, state);
    expect(changes).toHaveLength(1);
    const change = changes[0] as Extract<FileChange, { kind: "edit" }>;
    expect(change.path).toBe("guide/setup.md");
    expect(change.newContent).toContain("sidebar_label: Setup");
    // "The heading is never touched" used to be checked by finding it
    // inside newContent. It cannot be there any more — the plan carries
    // only the nav head — so the property is checked where it now lives:
    // the heading is absent from the plan, and survives the splice.
    expect(change.newContent).not.toContain("# Setting Up ##");
    expect(spliceNavHead(FILES["guide/setup.md"]!, change.newContent)).toContain(
      "# Setting Up ##",
    );
    // and it round-trips
    const patched = applyChanges(FILES, changes);
    const reparsed = docusaurusAdapter.parse(patched, "Site");
    expect(findTopic(reparsed.doc, "Setup")).toBeDefined();
  });
});

describe("_category_.yml (what facebook/docusaurus itself uses)", () => {
  // shaped after the real api/plugins/_category_.yml — nested link
  // block with an inline comment that MUST survive edits
  const YML_FILES: FilesSnapshot = {
    "api/plugins/_category_.yml":
      "label: Plugins\n" +
      "position: 2\n" +
      "link:\n" +
      "  type: doc\n" +
      '  id: api/plugins/plugins-overview # Dogfood using a "qualified id"\n',
    "api/plugins/overview.mdx": "---\ntitle: Overview\nsidebar_position: 1\n---\nA\n",
    "api/plugins/analytics.mdx": "---\ntitle: Analytics\n---\nB\n",
    "api/misc/_category_.yml": "label: Miscellaneous\nposition: 4\n",
    "api/misc/eslint.mdx": "---\ntitle: ESLint\n---\nC\n",
  };

  it("reads labels/positions from yml categories", () => {
    const { doc } = docusaurusAdapter.parse(YML_FILES, "API");
    const api = section(doc, "api");
    expect(api.topics.map((t) => t.title)).toEqual(["Plugins", "Miscellaneous"]);
    expect(docusaurusAdapter.detect(YML_FILES)).toBeGreaterThan(0.5);
  });

  it("LAW: no edits → [] (yml categories included)", () => {
    const { doc } = docusaurusAdapter.parse(YML_FILES, "API");
    const state: EditorState = {
      document: doc,
      columns: initialColumns(doc),
      view: { globalDepth: 2, cardDepths: {} },
    };
    expect(
      docusaurusAdapter.planChanges!(YML_FILES, doc, deriveSectionOrder(state.columns))
        .changes,
    ).toEqual([]);
  });

  it("renames a yml category via line surgery — nested comment survives", () => {
    const { doc } = docusaurusAdapter.parse(YML_FILES, "API");
    const plugins = findTopic(doc, "Plugins");
    const state = edit(doc, {
      type: "renameTopic",
      sectionId: plugins.sectionId,
      topicId: plugins.id,
      title: "Plugin APIs",
    });

    const { changes, warnings } = docusaurusAdapter.planChanges!(
      YML_FILES,
      state.document,
      deriveSectionOrder(state.columns),
    );
    expect(warnings.filter((w) => w.blocking)).toEqual([]);
    expect(changes).toHaveLength(1);
    const change = changes[0] as Extract<FileChange, { kind: "edit" }>;
    expect(change.path).toBe("api/plugins/_category_.yml");
    const before = YML_FILES[change.path]!.split("\n");
    const after = change.newContent.split("\n");
    expect(after.length).toBe(before.length);
    const diffs = before.filter((line, i) => after[i] !== line);
    expect(diffs).toEqual(["label: Plugins"]); // ONLY the label line
    expect(change.newContent).toContain("label: Plugin APIs");
    expect(change.newContent).toContain('# Dogfood using a "qualified id"');

    // idempotent + verified
    const sim = simulatePlan(
      docusaurusAdapter,
      YML_FILES,
      state.document,
      deriveSectionOrder(state.columns),
      changes,
    );
    expect(sim.ok).toBe(true);
    const patched = applyChanges(YML_FILES, changes);
    const reparsed = docusaurusAdapter.parse(patched, "API");
    expect(
      docusaurusAdapter.planChanges!(
        patched,
        reparsed.doc,
        deriveSectionOrder(initialColumns(reparsed.doc)),
      ).changes,
    ).toEqual([]);
  });

  it("warns and prefers .json when a folder has both spellings", () => {
    const files: FilesSnapshot = {
      ...YML_FILES,
      "api/plugins/_category_.json":
        '{\n  "label": "Plugins JSON",\n  "position": 2\n}\n',
    };
    const { doc, warnings } = docusaurusAdapter.parse(files, "API");
    expect(warnings.some((w) => w.kind === "duplicate-category")).toBe(true);
    const api = section(doc, "api");
    expect(api.topics[0]!.title).toBe("Plugins JSON");
  });
});

describe("property: any editing session yields a safe plan", () => {
  // HEAVY, NOT SLOW (a fast-check property over whole plans). Timed out under machine load at the
  // default 5s while passing in ~0.7s idle; the control group was a
  // clean tree failing identically, so the cause is contention, not a
  // regression. The explicit budget keeps that diagnosis from having to
  // be re-derived from a red suite.
  it(
    "random command sequences → blocking warnings OR (simulation ok ∧ idempotent)",
    { timeout: 20000 },
    async () => {
      const fc = (await import("fast-check")).default;
      const { randomCommand } = await import("@/commands/__tests__/arbitraries");

      fc.assert(
        fc.property(
          fc.array(fc.integer({ min: 1, max: 0x7fffffff }), { maxLength: 12 }),
          (seeds) => {
            const files = snapshot();
            const { doc } = docusaurusAdapter.parse(files, "Docs Site");
            let state: EditorState = {
              document: doc,
              columns: initialColumns(doc),
              view: { globalDepth: 2, cardDepths: {} },
            };
            for (const seed of seeds) {
              const cmd = randomCommand(state, seed);
              if (!cmd) continue;
              state = runCommand(state, cmd).next;
            }
            const order = deriveSectionOrder(state.columns);
            const { changes, warnings } = docusaurusAdapter.planChanges!(
              files,
              state.document,
              order,
            );
            if (warnings.some((w) => w.blocking)) return; // blocked — safe

            const sim = simulatePlan(
              docusaurusAdapter,
              files,
              state.document,
              order,
              changes,
            );
            expect(sim.ok).toBe(true);

            const patched = applyChanges(files, changes);
            const reparsed = docusaurusAdapter.parse(patched, "Docs Site");
            const again = docusaurusAdapter.planChanges!(
              patched,
              reparsed.doc,
              deriveSectionOrder(initialColumns(reparsed.doc)),
            );
            expect(again.changes).toEqual([]);
          },
        ),
        { numRuns: 25 },
      );
    },
  );
});
